/*
* @Author: wakouboy
* @Date:   2018-08-08 23:31:36
* @Last Modified by:   wakouboy
* @Last Modified time: 2019-01-16 13:52:36
*/
// export const SET_NAME = 'SET_NAME';
const types = {
  UPDATE_LOADING_PAGE: 'UPDATE_LOADING_PAGE',
  UPDATE_UPDATE_SUB_LIST: 'UPDATE_UPDATE_SUB_LIST',
  UPDATE_UPDATE_MAP_BY_DIM: 'UPDATE_UPDATE_MAP_BY_DIM',
  UPDATE_UPDATE_MAP_BY_SUB: 'UPDATE_UPDATE_MAP_BY_SUB',
  UPDATE_CHANGE_LEVEL_BY_PANEL: 'UPDATE_CHANGE_LEVEL_BY_PANEL',
  UPDATE_CHANGE_LEVEL_BY_MAP: 'UPDATE_CHANGE_LEVEL_BY_MAP',
  UPDATE_CHANGE_MODE: 'UPDATE_CHANGE_MODE',
  UPDATE_DRAW_PROJECTION: 'UPDATE_DRAW_PROJECTION',
  UPDATE_CHANGE_PROJ_IN_BROWSE_MODE: 'UPDATE_CHANGE_PROJ_IN_BROWSE_MODE',
  UPDATE_UPDATE_MAP: 'UPDATE_UPDATE_MAP',
  UPDATE_RESIZE: 'UPDATE_RESIZE',
  UPDATE_CHANGE_SUB_PROJ_OPACITY: 'UPDATE_CHANGE_SUB_PROJ_OPACITY',
}

export default types